//import { Geist, Geist_Mono } from "next/font/google";
import Context from "@/ContextHelper/Context";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Context>
          {children}
        </Context>
      </body>
    </html>
  );
}
